spring.application.name=springbootassesment2
spring.datasource.url=jdbc:postgresql://localhost:5432/mappingDb
spring.datasource.username=postgres
spring.datasource.password=tiger
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

server.port=8084